require("core.plugin_config.onedark")
require("core.plugin_config.lualine")
require("core.plugin_config.nvim-tree")
require("core.plugin_config.telescope")
require("core.plugin_config.treesitter")
require("core.plugin_config.lsp")
require("core.plugin_config.comment")
require("core.plugin_config.cmp")
require("core.plugin_config.conform")
require("core.plugin_config.nvim-ufo")
require("core.plugin_config.statuscol")
-- require("core.plugin_config.supermaven")
-- require("core.plugin_config.quarto") Dont need anymore, for a single module in blair class lmao
